const productsData = [
  {
    name: 'Russian Prince',
    image: 'http://dummyimage.com/127x100.png/ff4444/ffffff',
    brand: 'Aquavit Etheric Energizer',
    origin: 'Sweden',
    weight: 23,
    unit: 'SE',
    category: 'Breakfast & Milk',
    stocks: 94,
    price: 44.12,
  },
  {
    name: 'Bacon Strip Precooked',
    image: 'http://dummyimage.com/191x100.png/dddddd/000000',
    brand: 'Para Grass Pollen',
    origin: 'Brazil',
    weight: 71,
    unit: 'BR',
    category: 'Frozen Food',
    stocks: 41,
    price: 31.91,
  },
  {
    name: 'Tomato - Tricolor Cherry',
    image: 'http://dummyimage.com/161x100.png/cc0000/ffffff',
    brand: 'Hydrogen Peroxide',
    origin: 'Mozambique',
    weight: 5,
    unit: 'MZ',
    category: 'Biscuits & Snacks',
    stocks: 44,
    price: 1.13,
  },
  {
    name: 'Ketchup - Tomato',
    image: 'http://dummyimage.com/140x100.png/cc0000/ffffff',
    brand: 'Olive Leaf Antibacterial Foaming Hand Wash',
    origin: 'China',
    weight: 15,
    unit: 'CN',
    category: 'Meat & Seafood',
    stocks: 84,
    price: 74.31,
  },
  {
    name: 'Yogurt - Peach, 175 Gr',
    image: 'http://dummyimage.com/192x100.png/ff4444/ffffff',
    brand: 'Carbuncles Boils',
    origin: 'Portugal',
    weight: 33,
    unit: 'PT',
    category: 'Breakfast & Milk',
    stocks: 32,
    price: 86.65,
  },
  {
    name: 'Chicken - Base',
    image: 'http://dummyimage.com/223x100.png/dddddd/000000',
    brand: 'Enoxaparin Sodium',
    origin: 'Russia',
    weight: 19,
    unit: 'RU',
    category: 'Fruits & Vegetables',
    stocks: 29,
    price: 30.18,
  },
  {
    name: 'Artichokes - Knobless, White',
    image: 'http://dummyimage.com/111x100.png/5fa2dd/ffffff',
    brand: 'PCxx',
    origin: 'Poland',
    weight: 100,
    unit: 'PL',
    category: 'Rice Pasta and Grains',
    stocks: 89,
    price: 39.68,
  },
  {
    name: 'Chocolate - Feathers',
    image: 'http://dummyimage.com/184x100.png/cc0000/ffffff',
    brand: 'Midazolam HCl',
    origin: 'Indonesia',
    weight: 33,
    unit: 'ID',
    category: 'Fruits & Vegetables',
    stocks: 49,
    price: 98.99,
  },
  {
    name: 'Bagelers',
    image: 'http://dummyimage.com/139x100.png/cc0000/ffffff',
    brand: 'Paroxetine',
    origin: 'Guinea-Bissau',
    weight: 25,
    unit: 'GW',
    category: 'Rice Pasta and Grains',
    stocks: 100,
    price: 83.48,
  },
  {
    name: 'Squash - Sunburst',
    image: 'http://dummyimage.com/170x100.png/5fa2dd/ffffff',
    brand: 'Neutrogena Nourishing Eye Quad',
    origin: 'China',
    weight: 69,
    unit: 'CN',
    category: 'Meat & Seafood',
    stocks: 75,
    price: 76.39,
  },
  {
    name: 'Pork - Bacon, Sliced',
    image: 'http://dummyimage.com/215x100.png/dddddd/000000',
    brand: 'LOXAPINE SUCCINATE',
    origin: 'Netherlands',
    weight: 66,
    unit: 'NL',
    category: 'Frozen Food',
    stocks: 17,
    price: 85.55,
  },
  {
    name: 'Juice Peach Nectar',
    image: 'http://dummyimage.com/246x100.png/ff4444/ffffff',
    brand: 'Rite Aid',
    origin: 'Canada',
    weight: 96,
    unit: 'CA',
    category: 'Breakfast & Milk',
    stocks: 42,
    price: 89.04,
  },
  {
    name: 'Cheese - Gouda Smoked',
    image: 'http://dummyimage.com/113x100.png/dddddd/000000',
    brand: 'Crayola Radical Red Roll On Hand Sanitizer',
    origin: 'China',
    weight: 75,
    unit: 'CN',
    category: 'Frozen Food',
    stocks: 70,
    price: 83.21,
  },
  {
    name: 'Sauce - Salsa',
    image: 'http://dummyimage.com/108x100.png/5fa2dd/ffffff',
    brand: 'Peter Island Ultimate Sheer Dry Touch Sunscreen',
    origin: 'Venezuela',
    weight: 33,
    unit: 'VE',
    category: 'Biscuits & Snacks',
    stocks: 36,
    price: 75.04,
  },
  {
    name: 'Pepper - Red Thai',
    image: 'http://dummyimage.com/234x100.png/ff4444/ffffff',
    brand: 'healthy mama',
    origin: 'China',
    weight: 44,
    unit: 'CN',
    category: 'Biscuits & Snacks',
    stocks: 84,
    price: 65.8,
  },
  {
    name: 'Milk - 2%',
    image: 'http://dummyimage.com/227x100.png/cc0000/ffffff',
    brand: 'Cranberry Spice Antibacterial Foaming Hand Wash',
    origin: 'Sweden',
    weight: 41,
    unit: 'SE',
    category: 'Frozen Food',
    stocks: 19,
    price: 17.28,
  },
  {
    name: 'Lidsoupcont Rp12dn',
    image: 'http://dummyimage.com/152x100.png/ff4444/ffffff',
    brand: 'Buspirone Hydrochloride',
    origin: 'Spain',
    weight: 28,
    unit: 'ES',
    category: 'Fruits & Vegetables',
    stocks: 56,
    price: 74.63,
  },
  {
    name: 'Veal - Osso Bucco',
    image: 'http://dummyimage.com/174x100.png/cc0000/ffffff',
    brand: 'CLONIDINE HYDROCHLORIDE',
    origin: 'Guatemala',
    weight: 93,
    unit: 'GT',
    category: 'Fruits & Vegetables',
    stocks: 1,
    price: 92.07,
  },
  {
    name: 'Smoked Tongue',
    image: 'http://dummyimage.com/241x100.png/5fa2dd/ffffff',
    brand:
      'Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Warm Bronze',
    origin: 'Niger',
    weight: 5,
    unit: 'NE',
    category: 'Beverages',
    stocks: 23,
    price: 43.0,
  },
  {
    name: 'Cheese - Le Cru Du Clocher',
    image: 'http://dummyimage.com/204x100.png/dddddd/000000',
    brand: 'Dandelion',
    origin: 'Indonesia',
    weight: 62,
    unit: 'ID',
    category: 'Rice Pasta and Grains',
    stocks: 30,
    price: 83.69,
  },
  {
    name: 'Sardines',
    image: 'http://dummyimage.com/222x100.png/5fa2dd/ffffff',
    brand: 'Cyclophosphamide',
    origin: 'China',
    weight: 78,
    unit: 'CN',
    category: 'Fruits & Vegetables',
    stocks: 97,
    price: 82.64,
  },
  {
    name: 'Radish - Black, Winter, Organic',
    image: 'http://dummyimage.com/199x100.png/5fa2dd/ffffff',
    brand: 'BC',
    origin: 'Norway',
    weight: 60,
    unit: 'NO',
    category: 'Beverages',
    stocks: 12,
    price: 29.55,
  },
  {
    name: 'Tortillas - Flour, 10',
    image: 'http://dummyimage.com/177x100.png/cc0000/ffffff',
    brand: 'Clopidogrel Bisulfate',
    origin: 'China',
    weight: 20,
    unit: 'CN',
    category: 'Rice Pasta and Grains',
    stocks: 17,
    price: 28.02,
  },
  {
    name: 'Soup - Campbells Broccoli',
    image: 'http://dummyimage.com/239x100.png/cc0000/ffffff',
    brand: 'Propranolol Hydrochloride',
    origin: 'Iran',
    weight: 72,
    unit: 'IR',
    category: 'Fruits & Vegetables',
    stocks: 63,
    price: 84.34,
  },
  {
    name: 'Anisette - Mcguiness',
    image: 'http://dummyimage.com/193x100.png/5fa2dd/ffffff',
    brand: 'Imiquimod',
    origin: 'China',
    weight: 68,
    unit: 'CN',
    category: 'Rice Pasta and Grains',
    stocks: 41,
    price: 19.82,
  },
  {
    name: 'Sugar - Fine',
    image: 'http://dummyimage.com/210x100.png/cc0000/ffffff',
    brand: 'Breacold Children',
    origin: 'Philippines',
    weight: 26,
    unit: 'PH',
    category: 'Rice Pasta and Grains',
    stocks: 62,
    price: 72.01,
  },
  {
    name: 'Wine - Guy Sage Touraine',
    image: 'http://dummyimage.com/168x100.png/5fa2dd/ffffff',
    brand: 'Lorazepam',
    origin: 'Pakistan',
    weight: 91,
    unit: 'PK',
    category: 'Frozen Food',
    stocks: 1,
    price: 97.47,
  },
  {
    name: 'Spaghetti Squash',
    image: 'http://dummyimage.com/146x100.png/ff4444/ffffff',
    brand: 'Metformin Hydrochloride',
    origin: 'Thailand',
    weight: 66,
    unit: 'TH',
    category: 'Beverages',
    stocks: 42,
    price: 65.11,
  },
  {
    name: 'Horseradish - Prepared',
    image: 'http://dummyimage.com/133x100.png/ff4444/ffffff',
    brand: 'perfect truth cc broad spectrum SPF 30 sunscreen',
    origin: 'China',
    weight: 25,
    unit: 'CN',
    category: 'Rice Pasta and Grains',
    stocks: 59,
    price: 77.31,
  },
  {
    name: 'Cranberries - Dry',
    image: 'http://dummyimage.com/170x100.png/cc0000/ffffff',
    brand: 'Adidas',
    origin: 'Brazil',
    weight: 86,
    unit: 'BR',
    category: 'Meat & Seafood',
    stocks: 68,
    price: 32.82,
  },
  {
    name: 'Wine - Ej Gallo Sonoma',
    image: 'http://dummyimage.com/149x100.png/dddddd/000000',
    brand: 'CLONIDINE HYDROCHLORIDE',
    origin: 'Indonesia',
    weight: 73,
    unit: 'ID',
    category: 'Rice Pasta and Grains',
    stocks: 63,
    price: 83.9,
  },
  {
    name: 'Truffle Shells - White Chocolate',
    image: 'http://dummyimage.com/162x100.png/dddddd/000000',
    brand: 'ZENPEP',
    origin: 'Hungary',
    weight: 5,
    unit: 'HU',
    category: 'Breakfast & Milk',
    stocks: 78,
    price: 45.14,
  },
  {
    name: 'Wine - Dubouef Macon - Villages',
    image: 'http://dummyimage.com/130x100.png/dddddd/000000',
    brand: 'Ginger and Lemon Antibacterial Foaming Hand Wash',
    origin: 'Thailand',
    weight: 53,
    unit: 'TH',
    category: 'Beverages',
    stocks: 44,
    price: 53.33,
  },
  {
    name: 'Paper Cocktail Umberlla 80 - 180',
    image: 'http://dummyimage.com/143x100.png/dddddd/000000',
    brand: 'METHOTREXATE',
    origin: 'Indonesia',
    weight: 66,
    unit: 'ID',
    category: 'Frozen Food',
    stocks: 11,
    price: 13.58,
  },
  {
    name: 'Cheese - Provolone',
    image: 'http://dummyimage.com/165x100.png/cc0000/ffffff',
    brand: 'Aspergillus fumigatus',
    origin: 'China',
    weight: 10,
    unit: 'CN',
    category: 'Breakfast & Milk',
    stocks: 14,
    price: 6.91,
  },
  {
    name: 'Sauce - Chili',
    image: 'http://dummyimage.com/132x100.png/dddddd/000000',
    brand: 'Hand Sanitizer',
    origin: 'China',
    weight: 81,
    unit: 'CN',
    category: 'Meat & Seafood',
    stocks: 28,
    price: 33.44,
  },
  {
    name: 'Artichoke - Bottom, Canned',
    image: 'http://dummyimage.com/141x100.png/ff4444/ffffff',
    brand: 'Colgate Proclinical Refreshing Mint',
    origin: 'China',
    weight: 59,
    unit: 'CN',
    category: 'Meat & Seafood',
    stocks: 53,
    price: 45.29,
  },
  {
    name: 'Onions - Green',
    image: 'http://dummyimage.com/128x100.png/dddddd/000000',
    brand: 'Cetirizine Hydrochloride',
    origin: 'Philippines',
    weight: 36,
    unit: 'PH',
    category: 'Beverages',
    stocks: 98,
    price: 67.27,
  },
  {
    name: 'Table Cloth 90x90 Colour',
    image: 'http://dummyimage.com/179x100.png/5fa2dd/ffffff',
    brand: 'Adrenal Support',
    origin: 'Philippines',
    weight: 42,
    unit: 'PH',
    category: 'Frozen Food',
    stocks: 56,
    price: 41.47,
  },
  {
    name: 'Pork - Ham Hocks - Smoked',
    image: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
    brand: 'FocalinXR',
    origin: 'Philippines',
    weight: 28,
    unit: 'PH',
    category: 'Meat & Seafood',
    stocks: 15,
    price: 81.74,
  },
  {
    name: 'Foie Gras',
    image: 'http://dummyimage.com/224x100.png/ff4444/ffffff',
    brand: 'Members Mark Nicotine',
    origin: 'Russia',
    weight: 97,
    unit: 'RU',
    category: 'Breakfast & Milk',
    stocks: 84,
    price: 32.43,
  },
  {
    name: 'Lettuce - Romaine',
    image: 'http://dummyimage.com/175x100.png/ff4444/ffffff',
    brand: 'Truist Sunscreen Moisturizer',
    origin: 'Indonesia',
    weight: 59,
    unit: 'ID',
    category: 'Beverages',
    stocks: 83,
    price: 50.59,
  },
  {
    name: 'Flour - Corn, Fine',
    image: 'http://dummyimage.com/153x100.png/cc0000/ffffff',
    brand: 'SECRETIPSS SCALP HAIR ESSENTIAL BOOSTER',
    origin: 'Czech Republic',
    weight: 40,
    unit: 'CZ',
    category: 'Breakfast & Milk',
    stocks: 53,
    price: 97.77,
  },
  {
    name: 'Beer - Rickards Red',
    image: 'http://dummyimage.com/138x100.png/cc0000/ffffff',
    brand: 'Fosrenol',
    origin: 'Russia',
    weight: 84,
    unit: 'RU',
    category: 'Meat & Seafood',
    stocks: 61,
    price: 92.65,
  },
  {
    name: 'Cheese - Goat',
    image: 'http://dummyimage.com/106x100.png/ff4444/ffffff',
    brand: 'Leader Naproxen Sodium',
    origin: 'China',
    weight: 98,
    unit: 'CN',
    category: 'Biscuits & Snacks',
    stocks: 12,
    price: 24.22,
  },
  {
    name: 'Basil - Seedlings Cookstown',
    image: 'http://dummyimage.com/150x100.png/5fa2dd/ffffff',
    brand: 'NARS FOUNDATION',
    origin: 'Peru',
    weight: 44,
    unit: 'PE',
    category: 'Rice Pasta and Grains',
    stocks: 36,
    price: 18.25,
  },
  {
    name: 'Soup V8 Roasted Red Pepper',
    image: 'http://dummyimage.com/227x100.png/cc0000/ffffff',
    brand: 'HELIUM',
    origin: 'Russia',
    weight: 59,
    unit: 'RU',
    category: 'Rice Pasta and Grains',
    stocks: 95,
    price: 66.86,
  },
  {
    name: 'Ecolab - Hobart Washarm End Cap',
    image: 'http://dummyimage.com/215x100.png/dddddd/000000',
    brand: 'Excedrin',
    origin: 'Brazil',
    weight: 13,
    unit: 'BR',
    category: 'Biscuits & Snacks',
    stocks: 77,
    price: 72.97,
  },
  {
    name: 'Galliano',
    image: 'http://dummyimage.com/201x100.png/ff4444/ffffff',
    brand: 'Equaline antacid',
    origin: 'Thailand',
    weight: 37,
    unit: 'TH',
    category: 'Rice Pasta and Grains',
    stocks: 4,
    price: 29.04,
  },
  {
    name: 'Gin - Gilbeys London, Dry',
    image: 'http://dummyimage.com/197x100.png/5fa2dd/ffffff',
    brand: 'Nighttime Sinus',
    origin: 'Greece',
    weight: 63,
    unit: 'GR',
    category: 'Meat & Seafood',
    stocks: 35,
    price: 98.37,
  },
]

module.exports = productsData
